name: NekoPyonNews
options:
  bundleIdPrefix: com.tokyonasu
  deploymentTarget:
    iOS: "18.0"

settings:
  base:
    SWIFT_VERSION: 5.9
    TARGETED_DEVICE_FAMILY: "1"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "2"
    PRODUCT_BUNDLE_IDENTIFIER: com.tokyonasu.nekopyonnews
    DEVELOPMENT_TEAM: 83VGKGSQUH
    CODE_SIGN_STYLE: Automatic

targets:
  NekoPyonNews:
    type: application
    platform: iOS
    sources: [NekoPyonNews]
    settings:
      base:
        INFOPLIST_FILE: NekoPyonNews/Info.plist
        PRODUCT_NAME: NekoPyonNews
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: NekoPyonNews/Info.plist
      properties:
        CFBundleName: ねこぴょんニュース
        CFBundleDisplayName: ねこぴょんニュース
        CFBundleIconName: AppIcon
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "2"
        LSRequiresIPhoneOS: true
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
